# Challenge: Vapor Pressure Deficit

#### Rachel Veenstra

In [12]:
# Importing modules

import numpy as np

In [13]:
# Defining new function

def vpdfun(T, R):
    """
    Calculates vapor pressure deficit. 
    
    Inputs:
            (Temperature, Relative Humidity)
            Temperature must be in degrees Celsius.
            Relative Humidity must be a percentage.
            
            Can be passed as individual numbers, or an assigned variable (such as an array).
          
    Author: Rachel Veenstra
    Date: 04-Mar-2019
    """
    # Calculating saturated vapor pressure
    SVP = 0.611 * np.exp((17.5*T)/(T+241))
    
    # Calculating actual vapor pressure
    AVP = SVP*(R/100)
    
    # Calculating final vapor pressure deficit
    Final = (SVP - AVP).round(2)
    
    return Final

In [14]:
# Creating example input variables 

# 5x5 arrays of linear values in the desired ranges

temp_grid = np.linspace(0,40,25).reshape(5,5) 

RH_grid = np.linspace(0,100,25).reshape(5,5)

In [15]:
# Calling function and storing output as "VPD" variable

VPD = vpdfun(temp_grid, RH_grid)

print(VPD)

[[0.61 0.66 0.71 0.76 0.82]
 [0.87 0.92 0.97 1.02 1.06]
 [1.11 1.14 1.17 1.19 1.19]
 [1.19 1.16 1.12 1.06 0.97]
 [0.85 0.7  0.51 0.28 0.  ]]
