# Challenge: Vapor Pressure Deficit

#### Rachel Veenstra

In [1]:
# Importing modules

import numpy as np

In [46]:
# Defining new function

def vpdfun(T, R):
    """
    Calculates vapor pressure deficit. 
    
    Inputs:
            (Temperature, Relative Humidity)
            Temperature must be in degrees Celsius.
            Relative Humidity must be a percentage.
            
            Can be passed as individual numbers, or an assigned variable (such as an array).
          
    Author: Rachel Veenstra
    Date: 04-Mar-2019
    """
    SVP = 0.611 * np.exp((17.5*T)/(T+241))
    AVP = SVP*(R/100)
    Final = (SVP - AVP).round(2)
    return Final

In [44]:
# Creating example input variables (used random numbers for both variables)

temp_grid = np.random.randint(0,41,[5,5]) # creating 5x5 arrays of random values in the desired range
RH_grid = np.random.randint(1,101, [5,5]) 

In [47]:
# Calling function and storing output as "VPD" variable

VPD = vpdfun(temp_grid, RH_grid)
print(VPD)

[[2.57 2.33 0.77 1.21 0.63]
 [0.3  1.18 2.67 0.7  5.52]
 [1.67 0.22 0.07 5.87 0.26]
 [0.03 2.12 4.45 2.12 0.83]
 [0.48 0.24 2.08 3.28 1.39]]
